-- MySQL Script generated by MySQL Workbench
-- Fri Oct 23 23:24:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SoProno
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SoProno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SoProno` DEFAULT CHARACTER SET utf8 ;
USE `SoProno` ;

-- -----------------------------------------------------
-- Table `SoProno`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SoProno`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `adresse` LONGTEXT NULL,
  `phone` VARCHAR(45) NULL,
  `birthdate` DATETIME NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SoProno`.`quizz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SoProno`.`quizz` (
  `idquizz` INT NOT NULL,
  `namequizz` VARCHAR(255) NULL,
  PRIMARY KEY (`idquizz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SoProno`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SoProno`.`answer` (
  `idanswer` INT(11) NOT NULL AUTO_INCREMENT,
  `answertext` VARCHAR(255) NOT NULL,
  `correctanswer` TINYINT(1) NOT NULL,
  `idanswerquestion` INT(11) NOT NULL,
  PRIMARY KEY (`idanswer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SoProno`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SoProno`.`question` (
  `idquestion` INT(11) NOT NULL AUTO_INCREMENT,
  `questiontxt` VARCHAR(255) NOT NULL,
  `idquestionquizz` INT(11) NOT NULL,
  `questiontype` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idquestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SoProno`.`useranswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SoProno`.`useranswer` (
  `iduseranswer` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  `idanswer` INT(11) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`iduseranswer`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
